FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY testserver/server.go .
COPY go.mod go.sum ./

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o testserver testserver/server.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/testserver .

EXPOSE 8888

CMD ["./testserver", "8888"]